schema_version = "1.0.0"

id = "hw_mode_highlight"
version = "0.1.0"
name = "HW Mode Highlight"
tagline = "Highlight Blender headers based on the current mode"
maintainer = "Martin"
type = "add-on"

blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

tags = ["User Interface"]
